### ISSUE TITLE
Significance of 42ms event loop delay?

### ISSUE THREAD

**Issue by 03eltond** [mcollina/loopbench#1]
Just a bit curious, is there any significance to 42ms for the default maximum event loop delay?  If we want to make this "issue" actionable, we could say that whatever the answer is could be documented :)

Thanks for the library!

**Comment by mcollina** [comment]
I had to pick a number, and 42 was the answer.

Il giorno mar 24 set 2019 alle 19:38 03eltond <notifications@github.com> ha
scritto:

**Comment by 03eltond** [comment]
Oh wow lol. Can't believe I whiffed that reference, and now I'm on the world wide web looking like a fool.  Guess we can close!
